name: workflowRelease

on:
  push:
    branches: [ release* ]
  pull_request:
    branches: [ release*  ]
  schedule:
    - cron: '*/30 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Compilando o Projeto
        run: |
          echo "ðŸ”¨ Compilando o projeto Maven..."
          echo "Se essa build falhar, Ã© sÃ³ culpar o Hibernate! (brincadeira... ou nÃ£o) ðŸ˜…"

      - name: Compilar projeto
        run: echo "compilando projeto"

      - name: Etapa final
        run: echo "Step Executado com sucesso"