name: Desafio 3 - VariÃ¡veis do GitHub

on: [push, pull_request]

jobs:
  show-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir informaÃ§Ãµes do contexto GitHub
        run: |
          echo "ğŸ“Œ Nome do repositÃ³rio: ${{ github.repository }}"
          echo "ğŸ“Œ Branch atual: ${{ github.ref }}"
          echo "ğŸ“Œ Autor do commit: ${{ github.actor }}"
          echo "ğŸ“Œ SHA do commit: ${{ github.sha }}"
